version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    image: your-dockerhub-username/cloud-fe:latest
    container_name: cloud-fe-container
